/* Real-browser integration on synthetic saved-study fixtures and tiny CLI jobs.
 * Uses the same NODE_PATH / DASHBOARD_PYTHON / DASHBOARD_BROWSER_CHANNEL setup
 * as workbench_browser.cjs. Formal research data are neither changed nor run.
 */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { spawn } = require('node:child_process');
const { chromium } = require('playwright');
const root = path.resolve(__dirname, '..');
const output = path.join(root, 'output', 'playwright');
fs.mkdirSync(output, { recursive: true });
const fixture = fs.mkdtempSync(path.join(output, 'research-'));
const write = (name, text) => { const file = path.join(fixture, name); fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, text); return file; };
const json = (name, value) => write(name, JSON.stringify(value));
fs.cpSync(path.join(root, 'src', 'maxcover'), path.join(fixture, 'src', 'maxcover'), { recursive: true, filter: (file) => !file.includes('__pycache__') && !file.includes('dashboard_ui') });
fs.mkdirSync(path.join(fixture, 'analysis'));
for (const file of fs.readdirSync(path.join(root, 'analysis'))) if (file.endsWith('.py')) fs.copyFileSync(path.join(root, 'analysis', file), path.join(fixture, 'analysis', file));
fs.copyFileSync(path.join(root, 'counterexamples.py'), path.join(fixture, 'counterexamples.py'));
json('source.json', { universe_size: 6, k: 2, sets: [[0, 1, 2, 3], [0, 1, 4], [2, 3, 5]] });
write('experiments/r1_fixture/paths.jsonl', fs.readFileSync(path.join(root, 'experiments/r1_prefix_exchange_v1/paths.jsonl')));
json('results/r2_fixture/config.json', { version: 'r2-budget-v1' });
write('results/r2_fixture/budget_results.csv', 'base_graph_id,n,d,k,greedy,optimum,relative_gap\n' + Array.from({ length: 209 }, (_, i) => `g${i},12,3,2,8,9,0.1111111111111111\n`).join(''));
write('results/r2_fixture/cell_summary.csv', 'n,d,k,count,failures\n12,3,2,209,209\n');
write('results/r2_fixture/mechanism_summary.csv', 'n,d,k,count,failures\n12,3,2,209,209\n');
json('results/r2_fixture/run_status.json', { complete: false });
json('results/r2_fixture/verification.json', { status: 'passed', graphs: { g0: {} } });
json('results/r3_fixture/config.json', { version: 'r3-first-step-confirm-v1-fixture' });
json('results/r3_fixture/primary_summary.json', { n: 2, endpoints: 8, delta: 0.5, lower: -0.25, upper: 1, confidence: 0.95, direction: 'inconclusive' });
write('results/r3_fixture/base_graph_summary.csv', 'base_graph_id,difference\ng1,1\ng2,0\n');
write('results/r3_fixture/endpoint_results.csv', 'base_graph_id,chain_seed\ng1,18446744073709551615\n');
write('results/r4_fixture/budget_results.csv', 'base_graph_id,upper,initial_upper\ng1,7,8\n');
write('results/r4_fixture/cell_summary.csv', 'n,d,k,count\n12,3,2,1\n');
const python = process.env.DASHBOARD_PYTHON || 'python';
let server, browser, log = '';
function startServer() {
  server = spawn(python, ['-u', '-c', "import sys; from pathlib import Path; sys.path.insert(0, 'src'); from maxcover.dashboard import serve_dashboard; serve_dashboard(port=0, project_root=Path(sys.argv[1]))", fixture], { cwd: root, windowsHide: true, stdio: ['ignore', 'pipe', 'pipe'] });
  server.stderr.on('data', (chunk) => { log += chunk; });
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => reject(new Error('Server startup timeout: ' + log)), 20000);
    server.on('error', reject); server.on('exit', (code) => { clearTimeout(timer); reject(new Error('Server exited: ' + code + log)); });
    server.stdout.on('data', (chunk) => { const match = String(chunk).match(/http:\/\/127\.0\.0\.1:\d+\//); if (match) { clearTimeout(timer); resolve(match[0]); } });
  });
}
async function stopServer() { const exited = new Promise((resolve) => server.once('exit', resolve)); server.kill(); await exited; }
const checks = [], passed = (name) => { checks.push(name); console.log('PASS ' + name); };
(async () => {
  let url = await startServer();
  browser = await chromium.launch({ headless: process.env.DASHBOARD_HEADED !== '1', ...(process.env.DASHBOARD_BROWSER_CHANNEL ? { channel: process.env.DASHBOARD_BROWSER_CHANNEL } : {}) });
  const page = await browser.newPage({ viewport: { width: 1366, height: 960 } });
  const errors = []; page.on('pageerror', (error) => errors.push(error.message));
  await page.goto(url + 'research');
  await page.waitForFunction(() => document.querySelector('#study-count').textContent.includes('3 / 3'));
  await page.locator('#study-kind').selectOption('r3');
  await page.locator('#study-library button').click();
  await page.locator('#study-detail').waitFor();
  assert.match(await page.locator('#study-documents').innerText(), /原图数量 n\s+2/);
  assert.match(await page.locator('#study-documents').innerText(), /端点数\s+8/);
  assert.match(await page.locator('#study-tables').innerText(), /18446744073709551615/);
  await page.screenshot({ path: path.join(output, 'research-studies.png'), fullPage: true });
  passed('saved R2/R3/R4 discovery and R3 graph/endpoint units preserve the stored values and large seed');
  await page.locator('#study-kind').selectOption('r2'); await page.locator('#study-library button').click();
  await page.waitForFunction(() => document.querySelector('#study-source').textContent === 'results/r2_fixture' && !document.querySelector('#study-detail').hidden);
  assert.match(await page.locator('#study-statuses').innerText(), /历史记录.*未重新验证/);
  assert.match(await page.locator('#study-tables').innerText(), /200 \/ 209/);
  const downloadReady = page.waitForEvent('download');
  await page.locator('#study-tables section').filter({ has: page.getByRole('heading', { name: 'budget_results.csv', exact: true }) }).getByRole('link', { name: '下载完整 CSV' }).click();
  const download = await downloadReady, downloaded = path.join(fixture, 'download.csv'); await download.saveAs(downloaded);
  assert.equal(fs.readFileSync(downloaded, 'utf8'), fs.readFileSync(path.join(fixture, 'results/r2_fixture/budget_results.csv'), 'utf8'));
  passed('study preview reports 200/209 while download contains the full unchanged CSV; verification remains historical');
  await page.locator('#study-search').fill('absent-source'); assert.equal(await page.locator('#study-library button').count(), 0);
  await page.locator('#study-search').fill('');
  let release, started; const held = new Promise((resolve) => { release = resolve; }), seen = new Promise((resolve) => { started = resolve; });
  await page.route('**/api/studies/detail?**', async (route) => { started(); await held; await route.continue(); });
  await page.locator('#study-library button').click(); await seen; await page.locator('#nav-experiments').click(); release();
  await page.waitForTimeout(300); assert.equal(await page.locator('#view-experiments').isVisible(), true); assert.equal(await page.locator('#study-detail').isVisible(), false);
  await page.unroute('**/api/studies/detail?**');
  passed('empty source filters and late study responses cannot replace a newer navigation');
  await page.locator('#mine-source').selectOption('experiments/r1_fixture/paths.jsonl');
  assert.equal(await page.locator('#mine-population').inputValue(), 'all');
  await page.locator('#mine-input').fill('source.json'); await page.locator('#mine-top').fill('1'); await page.locator('#mine-evaluations').fill('50');
  await page.locator('#submit-mine').click(); await page.locator('#job-result').waitFor({ timeout: 30000 });
  assert.match(await page.locator('#job-summary').innerText(), /本任务独立验证\s+是/);
  assert.equal(await page.locator('.research-case-grid > div').count(), 2);
  assert.match(await page.locator('#job-cases').innerText(), /原始实例[\s\S]*最优选择见证[\s\S]*缩小后的实例/);
  const firstJob = await page.locator('#job-id').innerText();
  const caseReady = page.waitForEvent('download'); await page.locator('#job-artifacts').getByRole('link', { name: '下载 counterexample_001.json', exact: true }).click();
  const caseDownload = await caseReady, casePath = path.join(fixture, 'download-case.json'); await caseDownload.saveAs(casePath);
  assert.equal(JSON.parse(fs.readFileSync(casePath, 'utf8')).k, 2);
  await page.screenshot({ path: path.join(output, 'research-mining.png'), fullPage: true });
  passed('real mining job freezes a manual instance, validates it, shows original/reduced witnesses and exports a case');
  await page.locator('#nav-experiments').click(); await page.locator('#mode-refute').click();
  await page.locator('#refute-k').fill('4'); await page.locator('#submit-refute').click();
  assert.match(await page.locator('#research-message').innerText(), /k ≤ m/); assert.equal(await page.locator('#view-experiments').isVisible(), true);
  await page.locator('#refute-k').fill('2'); await page.locator('#submit-refute').click(); await page.locator('#job-result').waitFor({ timeout: 30000 });
  assert.match(await page.locator('#job-summary').innerText(), /找到反例/); assert.equal(await page.locator('.research-case-grid > div').count(), 1);
  passed('invalid structural conditions stay in the form; valid refutation finds and independently validates the known counterexample');
  await page.locator('#nav-experiments').click(); await page.locator('#refute-budget').fill('0'); await page.locator('#submit-refute').click(); await page.locator('#job-result').waitFor({ timeout: 30000 });
  assert.match(await page.locator('#job-summary').innerText(), /预算耗尽/); assert.match(await page.locator('#job-cases').innerText(), /没有可展示/);
  await page.locator('#nav-experiments').click(); await page.locator('#refute-budget').fill('10'); await page.locator('#refute-n').fill('2'); await page.locator('#refute-m').fill('2'); await page.locator('#refute-k').fill('1'); await page.locator('#refute-size').fill('1'); await page.locator('#submit-refute').click(); await page.locator('#job-result').waitFor({ timeout: 30000 });
  assert.match(await page.locator('#job-summary').innerText(), /指定有限域已穷尽/);
  passed('zero budget and exhausted finite domain have distinct conclusions with no stale counterexample');
  await page.locator('#nav-experiments').click(); await page.locator('#refute-combinations').fill('1'); await page.locator('#submit-refute').click(); await page.locator('#retry-job').waitFor({ timeout: 30000 });
  const failedJob = await page.locator('#job-id').innerText(); assert.match(await page.locator('#job-log').innerText(), /exact reference exceeds/);
  await page.locator('#retry-job').click(); await page.waitForFunction((id) => document.querySelector('#job-id').textContent !== id && !document.querySelector('#job-detail').hidden && !document.querySelector('#retry-job').hidden, failedJob, { timeout: 30000 });
  assert.match(await page.locator('#job-metadata').innerText(), new RegExp(failedJob));
  assert.equal(await page.locator('#job-result').isVisible(), false);
  passed('failed CLI jobs expose logs and retry creates a new job linked to the frozen predecessor');
  await page.locator('#nav-experiments').click(); await page.locator('#mode-mine').click(); await page.locator('#mine-input').fill('../outside.json'); await page.locator('#submit-mine').click();
  await page.locator('#research-message.error').waitFor(); assert.equal(await page.locator('#submit-mine').isEnabled(), true);
  passed('rejected input paths keep the editable form and re-enable submission');
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), true);
  await page.locator('#nav-jobs').click(); await page.locator('#jobs-body button').first().waitFor();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), true);
  await page.screenshot({ path: path.join(output, 'research-mobile.png'), fullPage: true });
  passed('forms, task table and detail fit a 390px viewport without page overflow');
  await page.locator('#nav-studies').click(); await stopServer(); url = await startServer();
  await page.goto(url + 'research'); await page.locator('#nav-jobs').click(); await page.waitForFunction(() => document.querySelectorAll('#jobs-body tr').length === 6);
  await page.locator('#jobs-body tr').filter({ hasText: firstJob }).getByRole('button', { name: '查看任务', exact: true }).click(); await page.locator('#job-result').waitFor();
  assert.match(await page.locator('#job-summary').innerText(), /本任务独立验证\s+是/);
  passed('all six persisted jobs and completed artifacts survive a real dashboard process restart');
  let releaseResult, resultStarted;
  const resultHeld = new Promise((resolve) => { releaseResult = resolve; }), resultSeen = new Promise((resolve) => { resultStarted = resolve; });
  await page.route(`**/api/research/jobs/${firstJob}/result`, async (route) => { resultStarted(); await resultHeld; await route.continue(); });
  await page.locator('#jobs-body tr').filter({ hasText: firstJob }).getByRole('button', { name: '查看任务', exact: true }).click(); await resultSeen;
  assert.equal(await page.locator('#job-result').isVisible(), false);
  await page.locator('#jobs-body tr').filter({ hasText: failedJob }).getByRole('button', { name: '查看任务', exact: true }).click();
  await page.waitForFunction((id) => document.querySelector('#job-id').textContent === id, failedJob); releaseResult(); await page.waitForTimeout(300);
  assert.equal(await page.locator('#job-id').innerText(), failedJob); assert.equal(await page.locator('#job-result').isVisible(), false);
  passed('a pending old job result clears its old exports and cannot replace a newer selected task');
  const storedJob = path.join(fixture, 'results/workbench_jobs', firstJob, 'job.json');
  const bytesBefore = fs.readFileSync(storedJob);
  await page.getByRole('button', { name: `归档任务 ${firstJob}`, exact: true }).click();
  await page.waitForFunction(() => document.querySelectorAll('#jobs-body tr').length === 5);
  await page.locator('#nav-studies').click(); await stopServer(); url = await startServer();
  await page.goto(url + 'research'); await page.locator('#nav-jobs').click();
  await page.waitForFunction(() => document.querySelectorAll('#jobs-body tr').length === 5);
  await page.locator('#show-archived-jobs').check();
  await page.getByRole('button', { name: `还原任务 ${firstJob}`, exact: true }).click();
  await page.getByRole('button', { name: `归档任务 ${firstJob}`, exact: true }).waitFor();
  await page.locator('#show-archived-jobs').uncheck();
  await page.waitForFunction(() => document.querySelectorAll('#jobs-body tr').length === 6);
  assert.deepEqual(fs.readFileSync(storedJob), bytesBefore);
  passed('completed job archive survives a server restart and restoration preserves its original record');
  await page.locator('#nav-studies').click();
  const catalog = path.join(fixture, 'results/.dashboard_local/catalog.sqlite3');
  fs.writeFileSync(catalog, 'damaged local archive database');
  await page.reload(); await page.locator('#nav-jobs').click();
  await page.waitForFunction(() => document.querySelectorAll('#jobs-body tr').length === 6);
  assert.match(await page.locator('#research-message').innerText(), /归档状态不可用/);
  assert.equal(await page.getByRole('button', { name: `归档任务 ${firstJob}`, exact: true }).count(), 0);
  await page.locator('#jobs-body tr').filter({ hasText: firstJob }).getByRole('button', { name: '查看任务', exact: true }).click();
  await page.locator('#job-result').waitFor();
  assert.deepEqual(fs.readFileSync(storedJob), bytesBefore);
  assert.equal(fs.readFileSync(catalog, 'utf8'), 'damaged local archive database');
  passed('a damaged archive database leaves original tasks and completed results accessible');
  assert.deepEqual(errors, []);
  fs.writeFileSync(path.join(output, 'research-browser-checks.json'), JSON.stringify({ checks, fixture, errors }, null, 2));
  console.log(`Completed ${checks.length} browser checks.`);
})().catch((error) => { console.error(error); process.exitCode = 1; }).finally(async () => { if (browser) await browser.close(); if (server && server.exitCode === null) await stopServer(); });
